{{ $enabled := false }}
{{- range $value := .Values.istiooperators }}
{{ if and ($value.enabled) (eq $enabled false) }}
{{ $enabled = true }}
{{- end }}
{{- end }}

{{- if and $enabled ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: istio-operator
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
    app.kubernetes.io/part-of: bigbang
    app.kubernetes.io/managed-by: flux
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}