{{- if and (.Values.istiooperator.enabled) (.Values.istiooperators.default.enabled) }}
{{- fail "Only one of '.Values.istiooperator' or `.Values.istiooperators.default` may be enabled." }}
{{- end }}

{{- if .Values.istiooperator.enabled }}
{{- if hasKey .Values.istiooperator "revision" }}
{{- if not (hasKey .Values.istio "revision") }}
{{- fail (printf "istio is missing revision %q." .Values.istiooperator.revision) }}
{{- end }}
{{- if ne .Values.istiooperator.revision .Values.istio.revision }}
{{- fail "Revision for istio and istio operator differ." }}
{{- end }}
{{- end }}
{{- include "values-secret" (dict "root" $ "package" .Values.istiooperator "name" "istio-operator" "defaults" (include "bigbang.defaults.istiooperator" .)) }}
{{- end }}

{{- define "bigbang.defaults.istiooperator" -}}
createNamespace: false
{{ if hasKey .Values.istiooperator "revision" }}
revision: {{ .Values.istiooperator.revision }}
{{ end }}
imagePullSecrets:
  - private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
{{- end -}}

{{- range $name, $values := .Values.istiooperators }}
{{- if $values.enabled }}
{{- if hasKey $values "revision" }}
{{- range $n, $v := $.Values.istios }}
{{- if eq $n $name }}
{{- if not (hasKey $v "revision") }}{{- fail (printf "istio %q is missing revision %q." $n $values.revision) }}{{- end }}
{{- if ne $v.revision $values.revision }}{{- fail (printf "Revision for istio %q and istio operator %q differ." $n $name) }}{{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{- if eq $name "default" }}{{- $name = "istio-operator" }}{{- else }}{{- $name = printf "istio-operator-%s" $name }}{{- end }}
{{- $defaults := include "bigbang.defaults.istiooperators" (dict "root" $ "package" $values) }}
{{- include "values-secret" (dict "root" $ "package" $values "name" $name "defaults" $defaults) }}
{{- end }}
{{- end }}

{{- define "bigbang.defaults.istiooperators" -}}
createNamespace: false
{{ if hasKey .package "revision" }}
revision: {{ .package.revision }}
{{ end }}
imagePullSecrets:
  - private-registry

networkPolicies:
  enabled: {{ .root.Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .root.Values.networkPolicies.controlPlaneCidr }}
{{- end -}}
