{{- if .Values.istiooperator.enabled }}
{{- $name := "istio-operator" -}}
{{- if hasKey .Values.istiooperator "revision" }}
{{- $name = print $name "-" .Values.istiooperator.revision -}}
{{- end }}
{{- include "values-secret" (dict "root" $ "package" .Values.istiooperator "name" $name "defaults" (include "bigbang.defaults.istiooperator" .)) }}
{{- end }}

{{- define "bigbang.defaults.istiooperator" -}}
createNamespace: false
{{ if hasKey .Values.istiooperator "revision" }}
revision: {{ .Values.istiooperator.revision }}
{{ end }}
imagePullSecrets:
  - private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
{{- end -}}
