{{- $fluxSettingsKiali := merge .Values.kiali.flux .Values.flux -}}
{{- if .Values.kiali.enabled }}
{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: kiali
  chart:
    spec:
      chart: {{ .Values.kiali.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: kiali
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsKiali | nindent 2 }}
  
  {{- if .Values.kiali.postRenderers }}
  postRenderers:
  {{ toYaml .Values.kiali.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-kiali-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-kiali-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-kiali-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or $istioEnabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if $istioEnabled }}{{ include "istioDependsOn" . }}{{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
