{{- if .Values.kiali.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.kiali "name" "kiali" "defaults" (include "bigbang.defaults.kiali" .)) }}
{{- end }}

{{- define "bigbang.defaults.kiali" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
hostname: {{ $domainName }}
domain: {{ $domainName }}

openshift: {{ .Values.openshift}}

istio:
  {{ include "istioEnabled" . }}
  kiali:
    gateways:
    - istio-system/{{ default "public" .Values.kiali.ingress.gateway }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
elasticsearch:
  enabled: {{ .Values.logging.enabled }}
cr:
  spec:
    server:
      web_port: "443"
    auth:
      {{- if .Values.kiali.sso.enabled }}
      strategy: openid
      openid:
        client_id: "{{ .Values.kiali.sso.client_id }}"
        disable_rbac: true
        issuer_uri: "https://{{ .Values.sso.oidc.host }}/auth/realms/{{ .Values.sso.oidc.realm }}"
        scopes:
        - openid
        - email
        username_claim: email
      {{- else }}
      strategy: token
      {{- end }}
    external_services:
      grafana:
        enabled: {{ dig "grafana" "enabled" true .Values.monitoring.values }}
        {{- $grafanaUrl := first (dig "istio" "grafana" "hosts" list .Values.monitoring.values) }}
        url: https://{{ tpl ($grafanaUrl | default (printf "%s.%s" "grafana" $domainName)) . }}
        {{- if (dig "grafana" "enabled" true .Values.monitoring.values) }}
        auth:
          {{- if (dig "grafana" "admin" "existingSecret" "" .Values.monitoring.values) }}
          {{- $userKey := (dig "grafana" "admin" "userKey" "admin-user" .Values.monitoring.values) }}
          {{- with lookup "v1" "Secret" "monitoring" .Values.monitoring.values.grafana.admin.existingSecret }}
          username: {{ (get .data $userKey | b64dec) | default "admin" }}
          {{- end }}
          {{- else }}
          username: {{ dig "grafana" "adminUser" "admin" .Values.monitoring.values }}
          {{- end }}
          password: "secret:grafana-auth:password"
        {{- end }}
      tracing:
        enabled: {{ .Values.jaeger.enabled }}
        {{- $tracingUrl := first (dig "istio" "jaeger" "hosts" list .Values.jaeger.values) }}
        url: https://{{ tpl ($tracingUrl | default (printf "%s.%s" "tracing" $domainName )) . }}
      istio:
        component_status:
          components:
            - app_label: istiod
              is_core: true
              is_proxy: false
            {{- include "istio.component.labels" . | indent 12 }}
    api:
      namespaces:
        # bigbang watches all!
        exclude: []
networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
  {{ include "ingressLabels" (dict "root" . "gateway" .Values.kiali.ingress.gateway) }}
{{- end -}}

{{- define "istio.component.labels" -}}
{{- $ingresses := .Values.istio.ingressGateways | default dict }}
{{- range $name, $values := .Values.istio.controlplanes }}
  {{- if $values.enabled }}{{- $_ := set $ingresses $name $values.ingressGateways }}{{- end }}
{{- end }}
{{- if hasKey .Values.istio.values "ingressGateways" }}
  {{- range $name, $values := .Values.istio.values.ingressGateways }}
    {{- if $values.enabled }}{{- $_ := set $ingresses $name $values.ingressGateways }}{{- end }}
  {{- end }}
{{- end }}
{{- range $name, $values := $ingresses.ingressGateways }}
- app_label: {{ $name }}
  is_core: true
  is_proxy: true
{{- end }}
{{- end -}}
