{{- $fluxSettingsTwistlock := merge .Values.twistlock.flux .Values.flux -}}
{{- if .Values.twistlock.enabled }}
{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: twistlock
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: twistlock
    app.kubernetes.io/component: "security"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: twistlock
  chart:
    spec:
      chart: {{ .Values.twistlock.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: twistlock
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsTwistlock | nindent 2 }}
  
  {{- if .Values.twistlock.postRenderers }}
  postRenderers:
  {{ toYaml .Values.twistlock.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-twistlock-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-twistlock-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-twistlock-values
      kind: Secret
      valuesKey: "overlays"

  # TODO: DRY this up
  {{- if or .Values.gatekeeper.enabled $istioEnabled }}
  dependsOn:
    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if $istioEnabled }}{{ include "istioDependsOn" . }}{{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
