{{- $controlplane := "istio" }}
{{- $enabled := false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $enabled) }}{{ $enabled = true }}{{- end }}
{{- if and $enabled (ne $name "default") (ne $name "deprecated") }}{{- $controlplane = printf "%s-%s" $controlplane $name }}{{- end }}
{{- end }}

{{- if and $enabled (not .Values.istio.enabled) }}
{{- $fluxSettingsIstioGw := .Values.flux -}}
{{- if hasKey .Values.istio "flux" }}{{- $fluxSettingsIstioGw = merge .Values.istio.flux .Values.flux -}}{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: istio-system
  chart:
    spec:
      chart: {{ .Values.istio.gatewayGit.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: istio-gateway
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsIstioGw | nindent 2 }}

  {{- if .Values.istio.postRenderers }}
  postRenderers:
  {{ toYaml .Values.istio.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-istio-gateway-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-istio-gateway-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-istio-gateway-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    - name: {{ $controlplane }}
      namespace: {{ .Release.Namespace }}
{{- end }}
