{{- if .Values.istiogateway.enabled }}
{{- $controlplane := "istio" }}
{{- range $name, $values := .Values.istios }}
{{- if and (ne $name "default") ($values.enabled) }}{{ $controlplane = printf "%s-%s" $controlplane $name }}{{- end }}
{{- end }}
{{- $fluxSettingsIstioGw := .Values.flux -}}
{{- if hasKey .Values.istiogateway "flux" }}{{- $fluxSettingsIstioGw = merge .Values.istiogateway.flux .Values.flux -}}{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: istio-system
  chart:
    spec:
      chart: {{ .Values.istiogateway.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: istio-gateway
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsIstioGw | nindent 2 }}

  {{- if .Values.istiogateway.postRenderers }}
  postRenderers:
  {{ toYaml .Values.istiogateway.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-istio-gateway-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-istio-gateway-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-istio-gateway-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    - name: {{ $controlplane }}
      namespace: {{ .Release.Namespace }}
{{- end }}
