{{ $enabled := .Values.istio.enabled | default false }}
{{- range $values := .Values.istio.controlplanes }}
{{ if and ($values.enabled) (eq $enabled false) }}{{ $enabled = true }}{{- end }}
{{- end }}

{{- if and $enabled .Values.istio.gateways }}
{{- include "values-secret" (dict "root" $ "package" .Values.istio.gateways "name" "istio-gateway" "defaults" (include "bigbang.defaults.gateway" .)) }}
{{- end }}

{{- define "bigbang.defaults.gateway" -}}
gateways:
  main: null
{{- range $name, $values := .Values.istio.gateways }}
  {{ $name | nindent 2 }}:
    selector:
      app: {{ $values.ingressGateway }}
    servers:
    - hosts:
      {{ tpl ($values.hosts | default (list) | toYaml) $ | nindent 8 }}
      port:
        name: https
        number: 8443
        protocol: HTTPS
      tls:
        credentialName: {{ $name }}-cert
        mode: {{ dig "tls" "mode" "SIMPLE" $values }}
{{- end }}
{{- end -}}
