{{ $istioEnabled := false }}
{{- if .Values.istio.enabled }}{{ $istioEnabled = true }}{{- else }}
{{- range $values := .Values.istios }}
{{ if and ($values.enabled) (eq $istioEnabled false) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
{{- end }}
{{- if and $istioEnabled ( or .Values.addons.authservice.enabled .Values.monitoring.sso.enabled .Values.jaeger.sso.enabled ) }}
apiVersion: v1
kind: Namespace
metadata:
  name: authservice
  labels:
    {{- if $istioEnabled }}
    istio-injection: enabled
    {{- end }}
    app.kubernetes.io/name: authservice
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}

