{{- if .Values.addons.velero.enabled }}
{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: "cluster-utilities"
    {{- include "commonLabels" . | nindent 4 }}
    {{- if $istioEnabled }}{{- include "istioInjectionLabel" .  | nindent 4}}{{- end }}
{{- end }}
