{{- if .Values.addons.velero.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.velero "name" "velero" "defaults" (include "bigbang.defaults.velero" .)) }}
{{- end }}

{{- define "bigbang.defaults.velero" -}}
{{ $istioEnabled := false }}
{{- range $values := .Values.istios }}{{ if and ($values.enabled) (eq $istioEnabled false) }}{{ $istioEnabled = true }}{{- end }}
{{- end -}}
hostname: {{ .root.Values.hostname }}

istio:
  enabled: {{ $istioEnabled }}

monitoring:
  enabled: {{ .root.Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .root.Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .root.Values.networkPolicies.controlPlaneCidr }}

imagePullSecrets:
- name: private-registry

{{- if eq (len .root.Values.addons.velero.plugins) 0 }}{{- fail "At least one plugin in '.root.Values.addons.velero.plugins' required. Supported values: aws, azure, csi" }}{{- end }}
initContainers:
{{- range .root.Values.addons.velero.plugins }}
{{- if eq . "aws" }}
  - name: velero-plugin-for-aws
    image: registry1.dso.mil/ironbank/opensource/velero/velero-plugin-for-aws:v1.2.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 100m
{{- end }}
{{- if eq . "azure" }}
  - name: velero-plugin-for-azure
    image: registry1.dso.mil/ironbank/opensource/velero/velero-plugin-for-microsoft-azure:v1.2.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 100m
{{- end }}
{{- if eq . "csi" }}
  - name: velero-plugin-for-csi
    image: registry1.dso.mil/ironbank/opensource/velero/velero-plugin-for-csi:v0.1.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 100m
configuration:
  features: EnableCSI
{{- end }}
{{- end }}

{{- end -}}
