{{- $fluxSettingsGitlab := merge .Values.addons.gitlab.flux .Values.flux -}}
{{- if .Values.addons.gitlab.enabled }}
{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  releaseName: gitlab
  targetNamespace: gitlab
  chart:
    spec:
      chart: {{ .Values.addons.gitlab.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: gitlab
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsGitlab | nindent 2 }}

  {{- if .Values.addons.gitlab.postRenderers }}
  postRenderers:
  {{ toYaml .Values.addons.gitlab.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-gitlab-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.gatekeeper.enabled $istioEnabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if .Values.gatekeeper.enabled }}
  - name: gatekeeper
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if $istioEnabled }}{{ include "istioDependsOn" . }}{{- end }}
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}