{{- if .Values.addons.nexus.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.nexus "name" "nexus-repository-manager" "defaults" (include "bigbang.defaults.nexus-repository-manager" .)) }}
{{- end }}

{{- define "bigbang.defaults.nexus-repository-manager" -}}
{{ $istioEnabled := false }}
{{- if .Values.istio.enabled }}{{ $istioEnabled = true }}{{- else }}
{{- range $values := .Values.istios }}
{{ if and ($values.enabled) (eq $istioEnabled false) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
{{- end }}
domain: {{ .Values.hostname }}
hostname: nexus
istio:
  enabled: {{ $istioEnabled }}
  nexus:
    gateways:
    - istio-system/{{ default "public" .Values.addons.nexus.ingress.gateway }}

openshift: {{ .Values.openshift }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  ingressLabels:
    {{- if .Values.istio.enabled }}
    {{- $gateway := default "public" .Values.addons.nexus.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.istio) | nindent 4 }}
    {{- end }}
    {{- range $name, $values := .Values.istios }}
    {{- $gateway := default "public" $.Values.addons.nexus.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil $values) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default $values) | nindent 4 }}
    {{- end -}}

nexus:
  imagePullSecrets:
    - name: private-registry

license_key: "{{ .Values.addons.nexus.license_key }}"

{{- if .Values.addons.nexus.sso.enabled }}
sso:
  enabled: {{ .Values.addons.nexus.sso.enabled }}
  idp_data:
    entityId: "https://nexus.{{ .Values.hostname }}/service/rest/v1/security/saml/metadata"
    usernameAttribute: "{{ .Values.addons.nexus.sso.idp_data.username }}"
    firstNameAttribute: "{{ .Values.addons.nexus.sso.idp_data.firstName }}"
    lastNameAttribute: "{{ .Values.addons.nexus.sso.idp_data.lastName }}"
    emailAttribute: "{{ .Values.addons.nexus.sso.idp_data.email }}"
    groupsAttribute: "{{ .Values.addons.nexus.sso.idp_data.groups }}"
    validateResponseSignature: "true"
    validateAssertionSignature: "true"
    idpMetadata: '{{ .Values.addons.nexus.sso.idp_data.idpMetadata }}'
  realm:
    - "NexusAuthenticatingRealm"
    - "NexusAuthorizingRealm"
    - "SamlRealm"
  role:
    id: "keycloak"
    name: "keycloak"
    description: "all keycloak users as admins"
    privileges:
      - "nx-all"
    roles:
      - "nx-admin"
{{- end }}
{{- end -}}
