{{- $fluxSettingsMonitoring := merge .Values.monitoring.flux .Values.flux -}}
{{- if .Values.monitoring.enabled }}
{{ $istioEnabled := false }}
{{- if .Values.istio.enabled }}{{ $istioEnabled = true }}{{- else }}
{{- range $values := .Values.istios }}
{{ if and ($values.enabled) (eq $istioEnabled false) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: {{ .Values.monitoring.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: monitoring
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsMonitoring | nindent 2 }}

  {{- if .Values.monitoring.postRenderers }}
  postRenderers:
  {{ toYaml .Values.monitoring.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-monitoring-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-monitoring-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-monitoring-values
      kind: Secret
      valuesKey: "overlays"

  # TODO: DRY this up
  {{- if or .Values.gatekeeper.enabled $istioEnabled }}
  dependsOn:
  {{- if $istioEnabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
