{{- if .Values.jaeger.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.jaeger "name" "jaeger" "defaults" (include "bigbang.defaults.jaeger" .)) }}
{{- end }}

{{- define "bigbang.defaults.jaeger" -}}
imagePullSecrets:
  - name: private-registry

# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
hostname: {{ $domainName }}
domain: {{ $domainName }}

istio:
  {{ include "istioEnabled" . }}
  jaeger:
    gateways:
    - istio-system/{{ default "public" .Values.jaeger.ingress.gateway }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
elasticsearch:
  enabled: {{ .Values.logging.enabled }}
{{- if .Values.jaeger.sso.enabled }}
jaeger:
  spec:
    {{- $jaegerAuthserviceKey := (dig "selector" "key" "protect" .Values.addons.authservice.values) }}
    {{- $jaegerAuthserviceValue := (dig "selector" "value" "keycloak" .Values.addons.authservice.values) }}
    allInOne:
      labels:
        {{ $jaegerAuthserviceKey }}: {{ $jaegerAuthserviceValue }}
    query:
      labels:
        {{ $jaegerAuthserviceKey }}: {{ $jaegerAuthserviceValue }}
{{- end }}
openshift:
  enabled: {{ .Values.openshift }}
networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
  {{ include "ingressLabels" (dict "root" . "gateway" .Values.jaeger.ingress.gateway) }}
{{- end -}}