{{- range $name, $values := .Values.istios }}
{{- if and (not $.Values.offline) $values.enabled }}
{{- if eq $name "default" }}
{{- $name = "istio-controlplane" }}
{{- else if hasKey $values "revision" }}
{{- $name = printf "istio-controlplane-%s" $values.revision }}
{{- else }}
{{- $name = printf "istio-controlplane-%s" $name }}
{{- end }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" $ | nindent 4}}
spec:
  interval: {{ $.Values.flux.interval }}
  url: {{ $values.git.repo }}
  ref:
    {{- include "validRef" $values.git | nindent 4 }}
  {{ include "gitIgnore" $ }}
  {{- include "gitCreds" $ | nindent 2 }}
---
{{- end }}
{{- end }}