{{- $deployName := "istiod" }}
{{- $controlplanes := dict "deprecated" .Values.istio }}
{{- range $name, $values := .Values.istio.controlplanes }}{{- $_ := set $controlplanes $name $values }}{{- end }}
{{- range $name, $values := $controlplanes }}
{{- if and (not $.Values.offline) $values.enabled }}
{{- if or (eq $name "default") (eq $name "deprecated") }}{{- $name = "istio-controlplane" }}{{- $deployName = "istiod" }}{{- else }}
{{- $deployName = printf "%s-%s" $deployName $name }}
{{- $name = printf "istio-controlplane-%s" $name }}
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}-hook
  namespace: istio-operator
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" $ | nindent 4}}
spec:
  template:
    metadata:
      name: {{ $name }}-hook
      labels:
        app.kubernetes.io/name: istio-controlplane
        app.kubernetes.io/component: "core"
        {{- include "commonLabels" $ | nindent 8}}
    spec:
      serviceAccountName: istio-operator
      restartPolicy: Never
      containers:
        - name: hook
          image: "registry1.dso.mil/ironbank/big-bang/base:8.4"
          command: ["kubectl"]
          args: ["rollout", "status", {{- printf "deployment/%s" $deployName | quote }}, "-n", "istio-system"]
{{- end }}
{{- end }}