{{ $enabled := .Values.istio.enabled | default false }}
{{- range $values := .Values.istio.controlplanes }}
{{ if and ($values.enabled) (eq $enabled false) }}{{ $enabled = true }}{{- end }}
{{- end }}

{{- if and $enabled (include "imagePullSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
