{{- $enabled := .Values.istio.enabled | default false }}
{{- range $values := .Values.istio.controlplanes }}
{{- if and ($values.enabled) (eq $enabled false) }}{{ $enabled = true }}{{- end }}
{{- end }}

{{- if $enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: disabled
{{- end }}