{{- if .Values.istio.enabled }}

{{/*
For backwards compatibility, get key/cert from .Values.istio.ingress
*/}}
{{- $default := .Values.istio.ingress | default dict -}}

{{- range $name, $values := .Values.istio.gateways }}
{{- if or (and (dig "tls" "cert" "" $values) (dig "tls" "key" "" $values)) (and $default.cert $default.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cert" $name }}
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" $ | nindent 4}}
type: kubernetes.io/tls
data:
  tls.crt: {{ default $default.cert $values.tls.cert | b64enc }}
  tls.key: {{ default $default.key $values.tls.key | b64enc }}
---
{{- end }}
{{- end }}

{{- end }}

{{- range $name, $values := .Values.istios }}
{{- if $values.enabled }}
{{- if eq $name "default" }}
{{- $name = "istio" }}
{{- else if hasKey $values "revision" }}
{{- $name = printf "istio-%s" $values.revision }}
{{- else }}
{{- $name = printf "istio-%s" $name }}
{{- end }}
{{/*
For backwards compatibility, get key/cert from .Values.istio.ingress
*/}}
{{- $default := $.Values.istio.ingress | default dict -}}
{{- range $n, $v := $values.gateways }}
{{- if or (and (dig "tls" "cert" "" $v) (dig "tls" "key" "" $v)) (and $default.cert $default.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if not (eq $name "istio") }}{{ $name }}-{{- end }}{{ printf "%s-cert" $n }}
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" $ | nindent 4}}
type: kubernetes.io/tls
data:
  tls.crt: {{ default $default.cert $v.tls.cert | b64enc }}
  tls.key: {{ default $default.key $v.tls.key | b64enc }}
---
{{- end }}
{{- end }}

{{- end }}
{{- end }}
