{{- if hasKey .Values.istiooperator "canary" }}
{{- $fluxSettingsIstioCanaryOperator := .Values.flux -}}
{{- if hasKey .Values.istiooperator.canary "flux" }}
{{- $fluxSettingsIstioCanaryOperator = merge .Values.istiooperator.canary.flux .Values.flux -}}
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator-{{- .Values.istiooperator.canary.revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: istio-operator
  chart:
    spec:
      chart: {{ .Values.istiooperator.canary.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: istio-operator-{{- .Values.istiooperator.canary.revision }}
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsIstioCanaryOperator | nindent 2 }}

  {{- if .Values.istiooperator.canary.postRenderers }}
  postRenderers:
  {{ toYaml .Values.istiooperator.canary.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-istio-operator-{{- .Values.istiooperator.canary.revision }}-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-istio-operator-{{- .Values.istiooperator.canary.revision }}-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-istio-operator-{{- .Values.istiooperator.canary.revision }}-values
      kind: Secret
      valuesKey: "overlays"

  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}