{{- $fluxSettingsFluentbit := merge .Values.fluentbit.flux .Values.flux -}}
{{- if .Values.fluentbit.enabled }}
{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: {{ .Values.fluentbit.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: fluentbit
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsFluentbit | nindent 2 }}

  {{- if .Values.fluentbit.postRenderers }}
  postRenderers:
  {{ toYaml .Values.fluentbit.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-fluentbit-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-fluentbit-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-fluentbit-values
      kind: Secret
      valuesKey: "overlays"

  {{/* ECK and Logging _always_ depend on .Values.logging being enabled, so can assume they exist here */}}
  dependsOn:
    - name: ek
      namespace: {{ .Release.Namespace }}
    {{- if  .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if $istioEnabled }}{{ include "istioDependsOn" . }}{{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
