{{- if .Values.fluentbit.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.fluentbit "name" "fluentbit" "defaults" (include "bigbang.defaults.fluentbit" .)) }}
{{- end }}

{{- define "bigbang.defaults.fluentbit" -}}
{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end -}}
elasticsearch:
  host: "logging-ek-es-http"
  password:
    secret: "logging-ek-es-elastic-user"

imagePullSecrets:
  - name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

istio:
  enabled: {{ $istioEnabled }}

{{- if .Values.monitoring.enabled }}
serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 10s
  scrapeTimeout: 10s
  selector:
    prometheus: monitoring-monitoring-kube-prometheus

dashboards:
  enabled: true
  labelKey: grafana_dashboard
  namespace: monitoring
{{- end }}

{{- if $istioEnabled }}
podLabels:
  traffic.sidecar.istio.io/excludeOutboundPorts: "443"
{{- end }}

{{- if .Values.openshift }}
podSecurityContext:
  seLinuxOptions:
    type: "spc_t"
{{- end }}
{{- end -}}
