{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $name, $values := .Values.istio.controlplanes }}
{{- if and $values.enabled (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
{{- $fluxSettingsHaProxy := merge .Values.addons.haproxy.flux .Values.flux -}}
{{- if and $istioEnabled .Values.monitoring.sso.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-sso
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/component: "developer-tools"
  {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: authservice
  chart:
    spec:
      chart: "./chart"
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: haproxy
        namespace: {{ .Release.Namespace }}
  {{- if .Values.addons.haproxy.postRenderers }}
  postRenderers:
  {{ toYaml .Values.addons.haproxy.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-haproxy-sso-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-haproxy-sso-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-haproxy-sso-values
      kind: Secret
      valuesKey: "overlays"

  {{- toYaml $fluxSettingsHaProxy | nindent 2 }}

  dependsOn:
    {{ include "istioDependsOn" . }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}

{{- end }}