{{- if .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.clusterAuditor "name" "cluster-auditor" "defaults" (include "bigbang.defaults.clusterauditor" .)) }}
{{- end }}

{{- define "bigbang.defaults.clusterauditor" -}}
{{- $istioEnabled := .Values.istio.enabled | default false }}
{{- range $values := .Values.istios }}
{{ if and ($values.enabled) (not $istioEnabled) }}{{ $istioEnabled = true }}{{- end }}
{{- end }}
elasticsearch:
  imagePullSecrets:
    - name: private-registry

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

istio:
  enabled: {{ $istioEnabled }}

openshift: {{ .Values.openshift }}
{{- end -}}
